export const ianLogo = 'https://i.postimg.cc/xdGZpPZd/logo.png'
export const githubLogo = 'https://i.postimg.cc/QMPZwWRy/github.png'
export const webIcon = 'https://i.postimg.cc/gJsQBQ8z/web.png'
export const arrowIcon = 'https://i.postimg.cc/hjf1jCQb/arrow.png'
export const menuIcon = 'https://i.postimg.cc/NFQj0vTV/menu.png'
export const closeIcon = 'https://i.postimg.cc/rm1pcwdx/close.png'
